// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/example/example_service.proto

package example

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_example_example_service_proto protoreflect.FileDescriptor

const file_api_example_example_service_proto_rawDesc = "" +
	"\n" +
	"!api/example/example_service.proto\x12+github.maximegorov13.grpc.proto.api.example\x1a\x1aapi/example/messages.proto2\xa6\x02\n" +
	"\aExample\x12\x8d\x01\n" +
	"\n" +
	"CreatePost\x12>.github.maximegorov13.grpc.proto.api.example.CreatePostRequest\x1a?.github.maximegorov13.grpc.proto.api.example.CreatePostResponse\x12\x8a\x01\n" +
	"\tListPosts\x12=.github.maximegorov13.grpc.proto.api.example.ListPostsRequest\x1a>.github.maximegorov13.grpc.proto.api.example.ListPostsResponseB\xab\x02\n" +
	"/com.github.maximegorov13.grpc.proto.api.exampleB\x13ExampleServiceProtoP\x01Z\x0fpkg/api/example\xa2\x02\x06GMGPAE\xaa\x02+Github.Maximegorov13.Grpc.Proto.Api.Example\xca\x02+Github\\Maximegorov13\\Grpc\\Proto\\Api\\Example\xe2\x027Github\\Maximegorov13\\Grpc\\Proto\\Api\\Example\\GPBMetadata\xea\x020Github::Maximegorov13::Grpc::Proto::Api::Exampleb\x06proto3"

var file_api_example_example_service_proto_goTypes = []any{
	(*CreatePostRequest)(nil),  // 0: github.maximegorov13.grpc.proto.api.example.CreatePostRequest
	(*ListPostsRequest)(nil),   // 1: github.maximegorov13.grpc.proto.api.example.ListPostsRequest
	(*CreatePostResponse)(nil), // 2: github.maximegorov13.grpc.proto.api.example.CreatePostResponse
	(*ListPostsResponse)(nil),  // 3: github.maximegorov13.grpc.proto.api.example.ListPostsResponse
}
var file_api_example_example_service_proto_depIdxs = []int32{
	0, // 0: github.maximegorov13.grpc.proto.api.example.Example.CreatePost:input_type -> github.maximegorov13.grpc.proto.api.example.CreatePostRequest
	1, // 1: github.maximegorov13.grpc.proto.api.example.Example.ListPosts:input_type -> github.maximegorov13.grpc.proto.api.example.ListPostsRequest
	2, // 2: github.maximegorov13.grpc.proto.api.example.Example.CreatePost:output_type -> github.maximegorov13.grpc.proto.api.example.CreatePostResponse
	3, // 3: github.maximegorov13.grpc.proto.api.example.Example.ListPosts:output_type -> github.maximegorov13.grpc.proto.api.example.ListPostsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_example_example_service_proto_init() }
func file_api_example_example_service_proto_init() {
	if File_api_example_example_service_proto != nil {
		return
	}
	file_api_example_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_example_service_proto_rawDesc), len(file_api_example_example_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_example_example_service_proto_goTypes,
		DependencyIndexes: file_api_example_example_service_proto_depIdxs,
	}.Build()
	File_api_example_example_service_proto = out.File
	file_api_example_example_service_proto_goTypes = nil
	file_api_example_example_service_proto_depIdxs = nil
}
